### ISSUE TITLE
Displayed messages sent

### ISSUE THREAD

**Issue by thaarhoff** [HYPERTEGRITY-AG/OpenSim#11]
When running OSCSim in timed mode (using switches  `--unlimited  --limit-time [RUN_TIME]`), the last displayed output does not reflect the actual number of messages sent (and also wrong calculations in msg/sec).

The output always misses some of the messages, so it might be, the output is stopped too early?

**Comment by WillFreitag** [comment]
Thanks for that finding!
Indeed, interrupting the threads after time is up prevented OSCSim from updating the display.
It's fixed in 1.1.2
